image:
  repository: dcristobal/pokemon-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.1"

replicaCount: 3 # Change this value to 3 for high availability

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: production.kcdlarioja.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - production.kcdlarioja.com
      secretName: production-kcdlarioja-tls
