image:
  repository: dcristobal/pokemon-app

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: staging.kcdlarioja.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - staging.kcdlarioja.com
      secretName: staging-kcdlarioja-tls
