version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: exampleuser
      DB_PASSWORD: examplepassword

    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
    restart: always
    networks:
      - my_network
    depends_on:
      - mysql
      - redis
      - memcached

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
      MYSQL_INITDB_SKIP_TZINFO: "true"
    volumes:
      - "./opt/db/database.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - my_network

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
