version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      env: production
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
    depends_on:
      - mysql
      - redis
      - memcached

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minipokedex
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: "true"
    volumes:
      - ./opt/db:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
