---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: manifests
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: core-apps
  path: "./kubernetes-apps/core/"
  prune: true
  timeout: 1m
