---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: ">=1.13.1"
  interval: 1h0m0s
  releaseName: external-dns
  targetNamespace: core
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    provider: cloudflare
    env:
      - name: CF_API_EMAIL
        value: cloudnativerioja@gmail.com
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            key: api-key
            name: cloudflare-api-key
    interval: 5m
    policy: sync
    txtOwnerId: fluxcloudnativerioja
    txtPrefix: fluxcloudnativerioja.
    logLevel: debug
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 256Mi
