---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: core-apps
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/dcristobalhMad/sre_task
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-big-cluster-manifests
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-manifests
  path: "./kubernetes-apps/secrets"
  prune: true
  timeout: 1m