---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dependencies
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: manifests
  sourceRef:
    kind: GitRepository
    name: core-apps
  path: "./kubernetes-apps/dependencies/"
  prune: true
  timeout: 1m
  wait: true
